[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn realtime_server:app --host 0.0.0.0"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10